### ISSUE TITLE
SBB validator not working

### ISSUE THREAD

**Issue by anandaguneratne** [sIKE23/Mage-Wars#162]
I don't know how much of the Spellbook builder we are in charge of, but the validator is not working (either on OCTGN or on the website)

**Comment by sIKE23** [comment]
What do you mean it is not working?

**Comment by anandaguneratne** [comment]
Well, I went into the OCTGN SBB, and tried to validate a deck. I got the following error message:

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Octgn.MageWarsValidator.ValidatorMenuItem.OnClick(IDeckBuilderPluginController con)
   at Octgn.DeckBuilder.DeckBuilderWindow.<>c__DisplayClass6.<.ctor>b__1(Object sender, RoutedEventArgs args) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\DeckBuilder\DeckBuilderWindow.xaml.cs:line 123

**Comment by sIKE23** [comment]
First lets make sure you are running the latest version of the SBB...

http://octgn.gamersjudgement.com/wordpress/magewars/install-2/sbb/

And we are responsible for the SBB, you will find it under the Deckbuilder
section in the Git repository.

//FC

**Comment by anandaguneratne** [comment]
Tested. It works!
