### ISSUE TITLE
OnTargetCardArrow throws error message when it targets a Domination Card Tile

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#236]
Traceback (most recent call last):
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 1933, in castSpell
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 2110, in computeCastCost
  File "<string>", line 1, in <module>
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 345, in onTargetCardArrow
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 2110, in <lambda$28>
ValueError: Invalid integer literal
onTargetCardArrow(Player(1), Card(65660), Card(65550), True)

**Comment by sIKE23** [comment]
@acg I made Internal and Mage Stats cards illegal targets if they are the toCard in the OnCardTargetArrow event.

**Comment by sIKE23** [comment]
This is fixed and working as expected now
