### ISSUE TITLE
Searching the Codex for "V’Torrak Artifact" generates Error

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#264]
Was showing the Domination Module to Charmyna and got this error. I am not sure of why it is happening at all. 

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\textfunctions.py", line 30, in searchCodex UnicodeEncodeError:  'unknown', '\x00', 0, 1, '') result = searchCodex(table, 119.650, 411.961)

**Comment by sIKE23** [comment]
Ah! I found it! Had to replace ’ with ' they are different!
