### ISSUE TITLE
Setup fails with more than three players

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#273]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 269, in finishSetup
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 293, in PlayerSetup
ValueError: too many values to unpack

**Comment by sIKE23** [comment]
Fixed
