### ISSUE TITLE
Harshforge Monolith Upkeep processing is broken

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#302]
From Sharkbait:

I get this when I click any option for Harshforge plate asking about upkeep

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 1028, in resolveUpkeep
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 1130, in processUpKeep
AttributeError: 'str' object has no attribute 'moveTo'
resolveUpkeep()

**Comment by sIKE23** [comment]
Resovled
