### ISSUE TITLE
Issue with Discard Pile Key

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#306]
Got the following error when a Bitterwood Fox died:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ananda\Documents\Mage-Wars\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 902, in damageBarrierStep
  File "C:\Users\Ananda\Documents\Mage-Wars\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 1127, in deathPrompt
  File "C:\Users\Ananda\Documents\Mage-Wars\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 553, in discard
  File "<string>", line 14, in __getitem__
KeyError: discard
damageBarrierStep({'Charge': 5, 'Flying': False, 'OwnerID': 65564, 'Fast': True, 'Living': True, 'Corporeal': True},{'Action': 'Quick', 'EffectType': 'Attack', 'Name': 'Bite', 'Traits': {'Piercing': 0}, 'Dice': 3, 'OriginalAttack': {'RangeType': 'Melee', 'Action': 'Quick', 'Traits': {}, 'SourceID': 65564, 'EffectType': 'Attack', 'd12': [], 'Name': 'Bite', 'Range': [0, 0], 'OriginalSourceID': 65564, 'Dice': 3}, 'SourceID': 65564, 'RangeType': 'Melee', 'OriginalSourceID': 65564, 'Range': [0, 0], 'd12': []},{'Charge': 5, 'OwnerID': 65563, 'Fast': True, 'Living': True, 'Corporeal': True})
```

The offending line of code appears to be:

```
card.moveTo(me.piles['Discard'])
```

In line 553 of actions.py

**Comment by sIKE23** [comment]
Was this in the release version or the 2.x version?

**Comment by ACG8** [comment]
It is a current issue in the 2.x version. I don't know whether it also occurs in the release version.
