### ISSUE TITLE
Implement Academy Weapons Attack Die increase for Level 5 and above Mages

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#341]

**Comment by sIKE23** [comment]
@ACG8 
```
Academy Weapons
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 651, in onCardArrowTargeted
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 61, in diceRollMenu
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 254, in getAttackList
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 221, in getAttackList
ValueError: invalid integer number literal

onCardArrowTargeted(EventArgument({"player":Player(1), "fromCard":Card(65629), "toCard":Card(65796), "targeted":True, "scripted":False}))
```

**Comment by sIKE23** [comment]
Never thought I was going to get this one done!
