### ISSUE TITLE
Define Single Zone for Academy

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#342]
We need to be able to have one large zone and be able to place the RDA appropriately

**Comment by ACG8** [comment]
I don't like the current academy board. For one thing, all the cards will be facing in the same direction; for another, it seems kind of busy. Could we just have a plain square arena?

**Comment by sIKE23** [comment]
Yeah I was just playing around a bit. O w going to put it back to just the
table top.

**Comment by ACG8** [comment]
Sounds good. For now, for testing purposes, I'm just going to set it to the 3x3 board; we can find a better image later.

**Comment by sIKE23** [comment]
I was just going to copy gameboard.png (the old "no board" image) to gameboard10.png.

**Comment by sIKE23** [comment]
Let me know if you like the idea and I will push the changes up to the repo.

//FC

**Comment by ACG8** [comment]
Sure, yes. Let's take a look.

**Comment by sIKE23** [comment]
It will be gameboard10 in the gamedef.....those sizes there may need to be
tuned...

//FC

**Comment by sIKE23** [comment]
@ACG8 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 651, in onCardArrowTargeted
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 86, in diceRollMenu
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 138, in isLegalAttack
  File "D:\Users\fczajka\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 549, in zoneGetDistance
TypeError: 'NoneType' object is not subscriptable

onCardArrowTargeted(EventArgument({"player":Player(2), "fromCard":Card(131085), "toCard":Card(65549), "targeted":True, "scripted":False}```

**Comment by sIKE23** [comment]
Would there be a chance that this could effect an Arena game?

```
"C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 1344, in computeTraits
  File "<string>", line 1, in <module>
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 1218, in resolveRegeneration
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 542, in cardGetDistance
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 545, in zoneGetDistance
TypeError: 'NoneType' object is unsubscriptable
resolveRegeneration()
Resolving Rot for sharkbait...
1 damage added to Warlord.
Finished auto-resolving Rot for sharkbait.
Traceback (most recent call last):
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attacks.py", line 1344, in computeTraits
  File "<string>", line 1, in <module>
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 986, in resolveDissipate
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 542, in cardGetDistance
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 545, in zoneGetDistance
TypeError: 'NoneType' object is unsubscriptable
resolveDissipate()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\actions.py", line 1096, in resolveUpkeep
  File "C:\Users\Sharkey\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 545, in zoneGetDistance
TypeError: 'NoneType' object is unsubscriptable
resolveUpkeep()
```
I think borders is returning None in the situation....

**Comment by sIKE23** [comment]
No I was not. But you bring up what is the issue. The placement of the
Monolith on one of the board edges leaves the potential to detect cards to
the side of the board on the table. In this case the RDA cards. I will
setup and test this, but I now believe that to be the issue. I will get
back to you and let you know. Thanks for the pointer!

//FC

**Comment by sIKE23** [comment]
So if add:

if aZone == None: continue

The loop should just continue with the next card?

Line 1112 in actions.py

**Comment by ACG8** [comment]
Yes, that should work, I think.
