### ISSUE TITLE
Mount - AlignMounted bug

### ISSUE THREAD

**Issue by sIKE23** [sIKE23/Mage-Wars#347]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\The Hero\Documents\Octgn\GameDatabase\9acef3d0-efa8-4d3f-a10c-54812baecdda\scripts\attachcards.py", line 451, in alignMounted
TypeError: int is not callable
alignMounted(Card(65562))

**Comment by sIKE23** [comment]
@ACG8 
This has been fixed it was an API thing.

**Comment by ACG8** [comment]
Ok, great.

**Comment by sIKE23** [comment]
Fixed
